#cloud-config

package_update: true
package_upgrade: true

users:
  - name: legrey
    groups: sudo,docker
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false

chpasswd:
  expire: false
  users:
    - name: legrey
      password: "12345678"
      type: text

ssh_pwauth: true

packages:
  - qemu-guest-agent
  - docker.io
  - docker-compose-v2

write_files:
  - path: /opt/postgres/docker-compose.yml
    permissions: "0644"
    content: |
      services:
        postgres:
          image: postgres:16
          restart: unless-stopped
          ports:
            - "5432:5432"
          environment:
            - POSTGRES_DB=n8n
            - POSTGRES_USER=n8n
            - POSTGRES_PASSWORD=n8n_pass_123
            - TZ=Europe/Kyiv
          volumes:
            - postgres_data:/var/lib/postgresql/data

      volumes:
        postgres_data:

runcmd:
  - systemctl enable --now ssh
  - systemctl enable --now qemu-guest-agent
  - systemctl enable --now docker
  - mkdir -p /opt/postgres
  - docker compose -f /opt/postgres/docker-compose.yml up -d
